server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show_sql: true
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
        format_sql: true

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
    
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE