server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:mysql://localhost:3306/tintin_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: tintin
    password: pass

  jpa:
    hibernate:
      ddl-auto: create
    show_sql: true
    open-in-view: false  # par defaut les db connections restent ouvertes pendant TOUT!  le traitement de la requete

decorator: 
  datasource: 
    flexy-pool:
      threshold: 
        connection:
          acquire: -1
          lease: 0